### ISSUE TITLE
repeat / timeStretch bug

### ISSUE THREAD

**Issue by devinmooers** [sebpiq/WAAClock#10]
So I'm not actually sure if this is a bug, but here's some sample code to try.

Run "WAABugTestInitWithBug()", then refresh page and run "WAABugTestInitWithWorkaround()". The test isn't quite perfect (meant to play 4 beats at 60 BPM, then 8 beats at 120 BPM), but I think it gets the idea across. There's this weird stuttering of events that happens when BPM changes / timeStretches are called in the callback function of callBackWithTime. I have to add a tiny setTimeout to fix this issue.

I'm relatively new to JS so haven't dived into the code - thoughts though? Is this a bug or is it the way it's supposed to work and I'm just not quite understanding it?

	var audioContext = window.AudioContext ? new AudioContext() : new webkitAudioContext();
	var clock = new WAAClock(audioContext);
	var bugTestMetronome;
	var WAACounter = 0;

	clock.start();

	// play 4 beats at 60 BPM, then 8 beats at 120 BPM (then cycle)
	function WAABugTestInitWithBug() {
		bugTestMetronome = clock.callbackAtTime(WAABugTestBangWithBug, audioContext.currentTime).repeat(1);
	}

	function WAABugTestInitWithWorkaround() {
		bugTestMetronome = clock.callbackAtTime(WAABugTestBangWithWorkaround, audioContext.currentTime).repeat(1);
	}

	function WAABugTestBangWithBug() {
		WAACounter++;
		console.log(WAACounter);
		if (WAACounter == 5) {
			WAABugTestDoubleTime();
		} else if (WAACounter == 11) {
			WAABugTestHalveTime();
			WAACounter = 0;
		}
	}

	function WAABugTestBangWithWorkaround() {
		// console.log(audioContext.currentTime);
		WAACounter++;
		console.log(WAACounter);
		clock.setTimeout(function() {
			if (WAACounter == 5) {
				WAABugTestDoubleTime();
			} else if (WAACounter == 11) {
				WAABugTestHalveTime();
				WAACounter = 0;
			}
		}, 0.0000001);
	}

	function WAABugTestHalveTime() {
		clock.timeStretch([bugTestMetronome], 2);
	}

	function WAABugTestDoubleTime() {
		clock.timeStretch([bugTestMetronome], 0.5);
	}

**Comment by sebpiq** [comment]
Yep ... it looks like your code should work fine ... so this is probably a bug. I'll have a look at it, thanks for the test case!

**Comment by devinmooers** [comment]
Yeah definitely! Thanks for the great library - I was trying to wrangle Web
Audio timing myself for a cellular automata music web app and not having a
great time of it until I found this. Cheers!

**Comment by sebpiq** [comment]
Glad it helps :)

On Tue, Feb 3, 2015 at 9:40 PM, devinmooers <notifications@github.com>
wrote:

> Yeah definitely! Thanks for the great library - I was trying to wrangle
> Web
> Audio timing myself for a cellular automata music web app and not having a
> great time of it until I found this. Cheers!
>
> On Tue, Feb 3, 2015, 5:13 AM Sebastien Piquemal <notifications@github.com>
>
> wrote:
>
> > Yep ... it looks like your code should work fine ... so this is probably
> a
> > bug. I'll have a look at it, thanks for the test case!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sebpiq/WAAClock/issues/10#issuecomment-72647584>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WAAClock/issues/10#issuecomment-72730033>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by sebpiq** [comment]
Should work like this now : 

```javascript
var audioContext = window.AudioContext ? new AudioContext() : new webkitAudioContext();
var clock = new WAAClock(audioContext);
var bugTestMetronome;
var WAACounter = -1;

clock.start();

// play 4 beats at 60 BPM, then 8 beats at 120 BPM (then cycle)
function WAABugTestInitWithBug() {
    bugTestMetronome = clock.callbackAtTime(WAABugTestBangWithBug, 1).repeat(1);
}
WAABugTestInitWithBug()

function WAABugTestInitWithWorkaround() {
    bugTestMetronome = clock.callbackAtTime(WAABugTestBangWithWorkaround, 0).repeat(1);
}

function WAABugTestBangWithBug() {
    WAACounter++;
    console.log(bugTestMetronome.deadline);
    if (WAACounter == 5) {
        WAABugTestDoubleTime();
    } else if (WAACounter == 11) {
        WAABugTestHalveTime();
        WAACounter = 0;
    }
}

function WAABugTestHalveTime() {
    clock.timeStretch(bugTestMetronome.deadline, [bugTestMetronome], 2);
}

function WAABugTestDoubleTime() {
    clock.timeStretch(bugTestMetronome.deadline, [bugTestMetronome], 0.5);
}
```

**Comment by dkmooers** [comment]
Works perfectly without setTimeout now! Thanks much, Sebastien.
