### ISSUE TITLE
Puase callbackAtTime

### ISSUE THREAD

**Issue by marcoturi** [sebpiq/WAAClock#17]
Is there away to just pause the method callbackAtTime ? Thanks for any suggetion.

**Comment by sebpiq** [comment]
Hi! What do you mean by "pause"? You can cancel the `callbackAtTime`, and reschedule the same for later ... if that's what you mean.

```
event.clear() // Pause event
event.schedule(time) // Restarts event at `time` (including repeats)
```

**Comment by marcoturi** [comment]
i found a better solution using suspend() and resume() on the context.

**Comment by sebpiq** [comment]
:+1:
