### ISSUE TITLE
Event Expired -- What am I supposed to do with events?

### ISSUE THREAD

**Issue by natotthomer** [sebpiq/WAAClock#19]
I'm absolutely loving a couple of the features in WAAClock, most notably the time stretching. (Am I wrong in thinking that the time stretch feature actually accurately stretches time even for events that have been already scheduled by callbackAtTime? If not, then I might have bigger problems.)

However, I'm getting dozens, hundreds of `event expired` warnings and I'm not sure what I'm supposed to do with them. I converted a metronome from the awesome (Tale of Two Clocks)[https://www.html5rocks.com/en/tutorials/audio/scheduling/] article into React and now I'm adding WAAClock. In the constructor for the main component, I set up my audioContext and clock:

    this.audioContext = new (window.AudioContext || window.webkitAudioContext)()
    this.clock = new WAAClock(this.audioContext)

On clicking a play button, I (surprise surprise), call the `play()` method, which looks like: 

    play () {
        const isPlaying = !this.state.isPlaying
        this.setState({ isPlaying })
        if (isPlaying) {
          this.clock.start()
          var secondsPerBeat = 60.0 / this.state.tempo
          this.event1 = this.clock.callbackAtTime(() => {
            this.scheduleNote(this.state.current16thNote)
            this.nextNote()
          }, 0).repeat(secondsPerBeat * this.state.noteLength)
        } else {
          this.event1.clear()
          this.clock.stop()
        }
      }

`scheduleNote()` simply turns on an oscillator at a specific time (`this.state.current16thNote`) and then turns it off 30 ms later. The second I press play, I get a stream of `event expired` warnings in my console and I'm really not sure what I'm supposed to do with them. Any help here would be very appreciated. You can find the full source for this [here](https://github.com/natotthomer/sequencer/blob/master/src/metronome.js)

**Comment by sebpiq** [comment]
Hi @natotthomer ! About the stretchTime I honestly don't remember how it behaves exactly ... I only remember there was a lot of arbitrary choices to make in how to design it :P you should check out the tests to see if it behaves like you expect.

About your "event expired", the problem is quite simple. You create your `AudioContext` way before, which means that `currentTime` is `t > 0` ... then when you start the clock, you schedule your first event at `currentTime = 0`, and set a repeat or `R`, and what the clock does is this : 

```
currentTime = t ; eventTime = 0 
  -> expired
  -> repeat
currentTime = t ; eventTime = 0 + R
  -> expired
  -> repeat
currentTime = t ; eventTime = 0 + 2 * R
  -> expired
  -> repeat
...
```
So to fix it, instead of scheduling `callbackAtTime` at `t = 0`, schedule it at `t = audioContext.currentTime`. Like so : 

```javascript
      this.event1 = this.clock.callbackAtTime(() => {
        this.scheduleNote(this.state.current16thNote)
        this.nextNote()
      }, audioContext.currentTime).repeat(secondsPerBeat * this.state.noteLength)
```

**Comment by natotthomer** [comment]
@sebpiq Brilliant! I had thought that it was an offset from `audioContext.currentTime` (ie, it would just wait the specified amount of time) rather than some specified point in time. Make sense? Either way, that worked perfectly. Going through the README, it makes more sense now. Thanks!
