### ISSUE TITLE
the clock doesn't work as expect

### ISSUE THREAD

**Issue by yilunshi** [sebpiq/WAAClock#22]
I'm new to web audio and I'm trying to use react and WAAClock to build a step sequencer. My problem happened when I started the clock and tried to add new events to it with calculated nextBeatTime(always ahead of current time). I upload the console so you can see only the first event scheduled at the same time as the clock start is working. All later attempts won't work. I'm not sure where's my mistake but I've already spent the whole day working on it and getting no result.  If you need to have a look at my code tell me and I will show you. Thanks a lot!
![image](https://user-images.githubusercontent.com/43126589/91628693-33f07c80-e977-11ea-868f-ff9e0f5df72c.png)

**Comment by sebpiq** [comment]
Closing as probably too old to answer anyways :/
