### ISSUE TITLE
Is this lib deprecated as createScriptProcessor is no longer available

### ISSUE THREAD

**Issue by apiel** [sebpiq/WAAClock#23]
WAAClock is using `createScriptProcessor` or this feature has been replaced by AudioWorklet, see:

https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createScriptProcessor

Does this mean this lib will no longer work?

**Comment by sebpiq** [comment]
Hello @apiel !
ScriptProcessorNode is indeed deprecated, but the library itself would work pretty much the same on an AudioWorklet. There is already a discussion to migrate it : #20 

I don't have the time to do it myself, but feel free to try it and I'd be happy to look over the code, give a hand and merge it back into the lib.
