### ISSUE TITLE
Callbacks still aren't reliably fired when tab is in the background

### ISSUE THREAD

**Issue by Smona** [sebpiq/WAAClock#26]
Hi @sebpiq! WAAClock has been working great for my project, but I noticed that callbacks are fired inconsistently when the tab is in the background. I know you aren't actively maintaining this, but I would be happy to take a shot at a PR. I just want to make sure I have all necessary context first.

I noticed a couple of attempts were made at fixing this issue, using both `setImmediate` and `process.nextTick`, but neither are used in the latest version, which reverts back to `setTimeout`. Was this just an accidental regression, or do we need to find a different approach?

Thanks!

**Comment by Smona** [comment]
For future readers: you can get reliable scheduling in background tabs by passing `tickMethod: "manual"` to the WAAClock options, and then using something like [worker-timers](https://github.com/chrisguttandin/worker-timers) to call `clock._tick()` every 10ms or so. Even though the option and method are undocumented, and you will get type errors.

**Comment by sebpiq** [comment]
@Smona thanks for the fix and sorry for not answering earlier! Would you consider sending a small PR to add this to documentation?
