### ISSUE TITLE
ios support

### ISSUE THREAD

**Issue by pjdowner** [sebpiq/WAAClock#6]
I've been looking at using this library for a project which I want to use on mobile devices, unfortunately it doesn't seem to work on ios I've been testing the web audio api and that works on an iphone that I have access to but this library does not. Alas I cannot give much more information as I just have an iphone I have borrowed for testing and as I don't have a Mac I can't enable remote debugging via safari.

**Comment by wattsie91** [comment]
Hi, I'm also looking to use your great library in an iOS Application but am having some difficulty. 
This works well in Chrome v40.0.22, Firefox v35.0, Safari v8.0.2
```javascript
var context = window.AudioContext ? new AudioContext() : new webkitAudioContext(), clock = new WAAClock(context);
var event = clock.callbackAtTime(function() { console.log('wow!') }, 13) 
```
but does not on iPad iOS 8.0, iPhone iOS 8.0.2... nor do your examples (basic sequencer) 
Having looked in console log I can see no errors, no logs and am finding quite hard to find where the fault is, wonder if you could give any insight? 

Thanks. Chris
