### ISSUE TITLE
Fix examples on iOS

### ISSUE THREAD

**Issue by chriswatts91** [sebpiq/WAAClock#9]
Hi, I'm also looking to use your great library in an iOS Application but having some difficulty. 
This works well in OS X Chrome v40.0.22, Firefox v35.0, Safari v8.0.2

``` javascript
var context = window.AudioContext ? new AudioContext() : new webkitAudioContext(), clock = new WAAClock(context);
var event = clock.callbackAtTime(function() { console.log('wow!') }, 13) 
```

but does not on iPad iOS 8.0, iPhone iOS 8.0.2... nor do your examples (basic sequencer) 
Having looked in console log I can see no errors, no logs and am having some difficulty finding where the fault is, wonder if you could give any insight? 

Thanks. Chris

**Comment by sebpiq** [comment]
Hi Chris! I use this library for a project of mine, we have tested it on various IPhones and IPads Safari + Chrome countless times ... With these platforms, there is a catch though which has nothing to do with WAAClock : you need to start the audiocontext on user event. Look here for more info : http://stackoverflow.com/questions/12517000/no-sound-on-ios-6-web-audio-api

However, you're right that I should update the examples to make them work like this ...

**Comment by wattsie91** [comment]
Hi, I came to the same conclusion when I realised the AudioContext.currentTime wouldn't count unless the audio context was started on a user event as you mention. Thanks!

**Comment by sebpiq** [comment]
Should be fixed now! I added a start button that should do the trick. If you could try that would be great as I don't have an iphone. Thx!

**Comment by wattsie91** [comment]
They don't seem to be working on iOS or Mac Safari (Console Log: "ReferenceError: Can't find variable: AudioContext"). Just next to add support for webkitAudioContext() as AudioContext() doesn't currently exist in iOS or Mac Safari.

**Comment by sebpiq** [comment]
Arr ... damn Safari for not following standards. Should work with Chrome
though!? I'll add support for the prefixed + old names.

On Mon, Mar 2, 2015 at 11:01 PM, Chris <notifications@github.com> wrote:

> They don't seem to be working on iOS or Mac Safari (Console Log:
> "ReferenceError: Can't find variable: AudioContext"). Just next to add
> support for webkitAudioContext() as AudioContext() doesn't currently exist
> in iOS or Mac Safari.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WAAClock/issues/9#issuecomment-76821542>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by wattsie91** [comment]
Chrome on iOS doesn't work either, wonder if that also uses webkitAudioContext()...

**Comment by sebpiq** [comment]
Ok ... I need to test that myself, when I get my hands on an iphone. Thanks
for this!

On Mon, Mar 2, 2015 at 11:19 PM, Chris <notifications@github.com> wrote:

> Chrome on iOS doesn't work either, wonder if that also uses
> webkitAudioContext()...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WAAClock/issues/9#issuecomment-76826417>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by k-ljung** [comment]
Any news about this?

**Comment by sebpiq** [comment]
This should do the trick! @k-ljung please tell me if it doesn't!!!
